// Generated by https://quicktype.io

export interface PrequalifiedCustomerResponse {
    data:            PrequalifiedCustomer;
    transactionId:   string;
    operationId:     string;
    statusCode:      number;
    transactionName: string;
}

export interface PrequalifiedCustomer {
    dpi:    string;
    name:   string;
    amount: number;
    quota:  number;
    period: number;
}

export interface PrequalifiedCustomerErrorResponse {
    errors:          string[];
    errorCode:       number;
    transactionId:   string;
    operationId:     string;
    statusCode:      number;
    transactionName: string;
}

